name: flutter_floor
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any

  # * Date Formatter
  date_format: ^2.0.7
  intl: ^0.18.1
  date_formatter: ^0.0.4

  # * Toast
  fluttertoast: ^8.2.4

  # * Floor Database
  floor: ^1.4.2
  sqflite: ^2.3.2

  # * Provider
  provider: ^6.1.1

  # * BLoC
  flutter_bloc: ^8.1.4

  # * Simple Data Persistent
  shared_preferences: ^2.2.2

  # * Dependency Injection
  get_it: ^7.6.7

  # * Simple Object Comparison
  equatable: ^2.0.5

  # * Icons
  ionicons: ^0.2.2

  # * Set Fonts From Google Fonts
  google_fonts: ^6.1.0

dev_dependencies:
  floor_generator: 1.4.2
  build_runner: 2.4.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
